### PR TITLE
fix: panic in case of non-retryable error with nil body

### LINKED ISSUE #648: Client panics when an HTTP request returns a client side error
- Algolia Client Version: v3.8.0
- Language Version: go 1.15.8

### Description

We have a service that is under high load. Sometimes at peak hours we are reaching your rate limits. When that happen, the the library returns an unhandled error. I think that the HTTP requests are failing with an error that occurs client side. Therefore the error's body is nil. That causes the `unmarshalTo` to panic.

```golang
        /usr/local/Cellar/go/1.15.8/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000186c00)
        /usr/local/Cellar/go/1.15.8/libexec/src/testing/testing.go:1075 +0x41a
panic(0x130e0a0, 0x1576ad0)
        /usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
encoding/json.(*Decoder).refill(0xc0001d6b00, 0x150, 0x1656e98)
        /usr/local/Cellar/go/1.15.8/libexec/src/encoding/json/stream.go:165 +0xb6
encoding/json.(*Decoder).readValue(0xc0001d6b00, 0x0, 0x0, 0x134b800)
        /usr/local/Cellar/go/1.15.8/libexec/src/encoding/json/stream.go:140 +0x1ff
encoding/json.(*Decoder).Decode(0xc0001d6b00, 0x12f0a20, 0xc0001933b0, 0x0, 0x0)
        /usr/local/Cellar/go/1.15.8/libexec/src/encoding/json/stream.go:63 +0x79
github.com/algolia/algoliasearch-client-go/v3/algolia/transport.unmarshalTo(0x0, 0x0, 0x1307ca0, 0xc0001aa680, 0xc000193390, 0xc0001d2b00)
        /Users/ralch/go/src/github.com/algolia/algoliasearch-client-go/algolia/transport/transport.go:305 +0xef
github.com/algolia/algoliasearch-client-go/v3/algolia/transport.unmarshalToError(0x0, 0x0, 0x0, 0x3b9aca00)
        /Users/ralch/go/src/github.com/algolia/algoliasearch-client-go/algolia/transport/transport.go:318 +0x65
github.com/algolia/algoliasearch-client-go/v3/algolia/transport.(*Transport).Request(0xc000195710, 0x12f5220, 0xc000193300, 0x1362423, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/ralch/go/src/github.com/algolia/algoliasearch-client-go/algolia/transport/transport.go:137 +0x97c
github.com/algolia/algoliasearch-client-go/v3/algolia/transport.TestShouldNotPanicOnError(0xc000186c00)
        /Users/ralch/go/src/github.com/algolia/algoliasearch-client-go/algolia/transport/transport_test.go:114 +0x2b0
testing.tRunner(0xc000186c00, 0x137bff0)
```

### Steps To Reproduce

I created a sample test that shows the exact error that occurs on our platform. Please have a look at my fork and this [commit](https://github.com/svett/algoliasearch-client-go/commit/87fb6ac1cec89701764dee60fa10d9c973e84a53).

### PR DESCRIPTION
**Pull request by VladislavFitz**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no   
| Related Issue     | Fix #648
| Need Doc update   | no

## Describe your change

In case of non-retryable transport error with nil body, the error is returned directly skipping the attempt to parse the body. 

## What problem is this fixing?

A few HS tickets ([1](https://secure.helpscout.net/conversation/1436477033/335677/), [2](https://secure.helpscout.net/conversation/1434758878/335102?folderId=2966557)) reported the panic happened due to attempt to unmarshal the nil body in case of non-retryable error.

### CODE REVIEW

File: algolia/transport/transport.go [hunk 1]
```diff
@@ -135,7 +135,9 @@ func (t *Transport) Request(
 			cancel()
 			return err
 		case Failure:
-			err = unmarshalToError(bodyRes)
+			if bodyRes != nil {
+				err = unmarshalToError(bodyRes)
+			}
```
Comment (marchelbling) [inline algolia/transport/transport.go:140]: should we have a default error as fallback value here or are we sure we will return an actual `err` in case `bodyRes == nil`?

Comment (VladislavFitz) [reply algolia/transport/transport.go:142]: Good point! Fixed ✔️

**Review by marchelbling — APPROVED** [review]
👌 

Side note: was it expected that we have an empty response body?
Is there an issue on the targeted API endpoints?

**Review by Nagriar — APPROVED** [review]
