### PR TITLE
fix(indexing): replaceAllObjects blocked if called for non-existent index

### LINKED ISSUE #694: ReplaceAllObjects hangs indefinitely if the index does not exist
```
github.com/algolia/algoliasearch-client-go/v3 v3.25.0
```

I'm pretty sure this has worked at one point.

I'm using it like this:

```go
index := client.InitIndex(indexName)
res, err := index.ReplaceAllObjects(iter, opt.Safe(true))

if err != nil {
	return err
}
return res.Wait()
```

I can see the `tmp` index being created with the correct amount of rows. If I manually create `indexName` before running the above, everything is OK.

My workaround is to use `SaveObjects` for non-existing indices.

### PR DESCRIPTION
**Pull request by VladislavFitz**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no     
| Related Issue     | Fix #694 
| Need Doc update   | no

## Describe your change

Add a check if the index exists in the `ReplaceAllObjects` function body.
If the index doesn't exist, only the `SaveObjects` operation will be executed which creates the index and saves the provided objects into it.

## What problem is this fixing?

`ReplaceAllObjects` hangs indefinitely if the index does not exist (#694). This happens due to infinite `CopyIndex` task when called for a non-existent index: the task successfully starts successfully but never accomplishes.

### CODE REVIEW

File: algolia/search/index_objects.go [hunk 1]
```diff
@@ -344,6 +344,27 @@ func (i *Index) browserForObjects(params searchParams, opts ...interface{}) func
 // prevent issues, one may want to pass the opt.Safe(true) option. Note that
 // passing this option will make the method blocking.
 func (i *Index) ReplaceAllObjects(objects interface{}, opts ...interface{}) (g *wait.Group, err error) {
+
```
Comment (samouss) [inline algolia/search/index_objects.go:347]:
```suggestion
```

File: algolia/search/index_objects.go [hunk 2]
```diff
@@ -344,6 +344,27 @@ func (i *Index) browserForObjects(params searchParams, opts ...interface{}) func
...
+	indexExists, err := i.Exists()
+	if err != nil {
+		err = fmt.Errorf("cannot check if the index exists: %v", err)
+		return
+	}
+
+	if !indexExists {
+		resSaveObjects, e := i.SaveObjects(objects, opts...)
+		if e != nil {
+			err = fmt.Errorf("cannot save objects to the index: %v", err)
```
Comment (samouss) [inline algolia/search/index_objects.go:359]:
```suggestion
			err = fmt.Errorf("cannot save objects to the index: %v", e)
```

File: algolia/search/index_objects.go [hunk 3]
```diff
@@ -344,6 +344,27 @@ func (i *Index) browserForObjects(params searchParams, opts ...interface{}) func
 // prevent issues, one may want to pass the opt.Safe(true) option. Note that
 // passing this option will make the method blocking.
 func (i *Index) ReplaceAllObjects(objects interface{}, opts ...interface{}) (g *wait.Group, err error) {
+
+	safe := iopt.ExtractSafe(opts...).Get()
+
+	indexExists, err := i.Exists()
```
Comment (samouss) [inline algolia/search/index_objects.go:350]:
```suggestion
	exists, err := i.Exists()
```

File: algolia/search/index_objects.go [hunk 4]
```diff
@@ -344,6 +344,27 @@ func (i *Index) browserForObjects(params searchParams, opts ...interface{}) func
...
+	if err != nil {
+		err = fmt.Errorf("cannot check if the index exists: %v", err)
+		return
+	}
+
+	if !indexExists {
```
Comment (samouss) [inline algolia/search/index_objects.go:356]:
```suggestion
	if !exists {
```

File: algolia/search/index_objects.go [hunk 5]
```diff
@@ -344,6 +344,27 @@ func (i *Index) browserForObjects(params searchParams, opts ...interface{}) func
...
+		resSaveObjects, e := i.SaveObjects(objects, opts...)
+		if e != nil {
+			err = fmt.Errorf("cannot save objects to the index: %v", err)
+			return
+		}
+		if safe {
+			resSaveObjects.Wait()
```
Comment (samouss) [inline algolia/search/index_objects.go:363]: I think we have to check for the returned error of `Wait`.

Comment (VladislavFitz) [reply algolia/search/index_objects.go]: Done ✅

**Review by samouss — APPROVED** [review]
